port_project/backend/urls.py
from django.urls import path
from backend import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'backend'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('view-profile/', views.view_profile, name='view_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('view-blog/', views.view_blog, name='view_blog'),
    path('add-blog/', views.add_blog, name='add_blog'),
    path('delete_blog/<slug:slug>/', views.delete_post, name='delete_blog'),
    path('edit-blog/<slug:slug>/', views.edit_post, name='editpost'),
    path('view-blogpost/<slug:slug>/', views.view_post, name='view_blogpost'),
    path('change_password/', views.password_change, name='change_password'),
    path('logout_view-page/', views.signout, name='logout_view'),
    path('signin/',views.signin, name='signin'),
    
    
    
]

port_project/port_app/urls.py
from unicodedata import name
from django.urls import path
from port_app import views
from django.conf import settings
from django.conf.urls.static import static
from port_app.views import Blog

app_name = 'port_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
    path('register/', views.register, name='register'),
    path('blog-details/<slug:slug>/', views.blog_detail, name='detail_blog'),
    
    # path('blog-details/<slug:slug>/', views.blog_detail.as_view(model=Blog), name='detail_blog'),
   
]


port_project/port_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from port_app import  views


urlpatterns = [
    path('',views.index, name='index'),
    path('port_app/', include('port_app.urls')),
    path('', include('backend.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    
]
  

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
                         
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


port_project/backend/models.py
from ast import mod
import email
from email.mime import image
from django.db import models
from random import choices


# Create your models here.    
    
class Profile(models.Model):
    username = models.CharField(max_length=20)
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    email = models. EmailField()
    
    def __str__(self):
        return self.firstname
        
    
    

port_project/backend/views.py
from audioop import add
import http
from urllib import response
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from backend.form import *
from django.contrib import messages
from backend.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout






# Create your views here.          
def signin(request):
    if request.method == 'POST':
        username = request.POST['user_name']
        password = request.POST['password']
            
        user = authenticate(request, username=username, password=password)
            
        if user is not None:
            login(request, user)
            return redirect('backend:dashboard')
    else:
        messages.error(request, '')
    return render(request, 'backend/signin.html')
 
 
 
@login_required(login_url='/signin/')
def dashboard(request):
    return render(request, 'backend/dashboard.html')

@login_required(login_url='/signin/')
def view_profile(request):
    view_profile = Profile.objects.filter()
    return render(request, 'backend/view-profile.html', {'profile':view_profile})

@login_required(login_url='/signin/')
def edit_profile(request):
    if request.method == 'POST':
        edit_profile = EditProfileForm(request.POST, instance=request.user)
        if edit_profile.is_valid():
            edit_profile.save()
            messages.success(request, 'Profile Edited Successfully')
            return redirect('backend:edit_profile')
    else:
            edit_profile=EditProfileForm()
    return render(request, 'backend/edit-profile.html', {'edit_pro':edit_profile})

@login_required(login_url='/signin/')
def view_blog(request):
    view_blog = Blog.objects.filter(user=request.user) 
    return render(request, 'backend/view-blog.html', {'view':view_blog})

@login_required(login_url='/signin/')
def add_blog(request):
    if request.method == 'POST':
        blog = AddBlogForm(request.POST,request.FILES)
        if blog.is_valid():        
            blog.save()
            blog = AddBlogForm()
            messages.success(request, 'Blog Posted')
    else:
        blog = AddBlogForm()
    return render(request, 'backend/add-blog.html', {'blog':blog})

# for dashboard blog edit, view and delete

@login_required(login_url='/signin/')
def edit_post(request, slug):
    single_blog = get_object_or_404(Blog, slug=slug)
    if request.method == 'POST':
        editform =EditBlogForm(request.POST, request.FILES, instance=single_blog)
        if editform.is_valid():
            blogf = editform.save(commit=False)
            blogf.user = request.user
            blogf.save()
            # messages.success(request, 'Blog Edit Successfully')
            return redirect('backend:view_blog')
        
    else: 
        editform = EditBlogForm(instance=single_blog)
    return render(request, 'backend/edit-blogpost.html', {'edit':editform})



# def edit_post(request, slug):
#     editpost = get_object_or_404(Blog, slug=slug)
#     if request.method == 'POST':
#         form = EditBlogForm(request.POST, request.FILES, instance=editpost)   
#         if form.is_valid():
#             editpost = form.save(commit=False)
#             editpost.save()          
#             messages.success(request, 'Blog Edited Successfully')
#             return redirect('backend:view_blog')             
#     else:
#         form = EditBlogForm(instance=editpost)
#         return render(request, 'backend/edit-blogpost.html', {'form':form})

@login_required(login_url='/signin/')
def view_post(request, slug):
    view_blogpost = get_object_or_404(Blog, slug=slug)
    return render(request, 'backend/viewblog_post.html', {'post':view_blogpost})
    
@login_required(login_url='/signin/')
def delete_post(request, slug):
    post_record = get_object_or_404(Blog, slug=slug)
    post_record.delete()
    return redirect('backend:view_blog')

@login_required(login_url='/signin/')
def password_change(request):
    if request.method == 'POST':
        pass_form = PasswordChangeForm(data=request.POST,
        user=request.user)
        if pass_form.is_valid():
            pass_form.save()
            update_session_auth_hash(request, pass_form.user)
            messages.success(request, 'Password changed successfully.')
    else:
        pass_form = PasswordChangeForm(user=request.user)
    return render(request, 'backend/change_password.html', {'pass_key':pass_form})

@login_required(login_url='/signin/')
def signout(request):
    logout(request)
    return redirect('backend:signin')
                

port_project/templates/backend/add-blog.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html> 

{% block title%}
Home
{% endblock %}

{% block content %}

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">Add Blog</h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Forms</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add Blog</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Add your blog</h4>
              <form method="post" enctype="multipart/form-data">
                {% if messages %}
                {% for m in messages %}
                <div class="alert alert-success">{{m}}</div>
                {% endfor %}
                {% endif %}
               {{blog.as_p}}
               {% csrf_token %}
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
               
              </form>
            </div>
          </div>
        </div>   
                        
                            
                            
           




{% endblock %}

port_project/templates/backend/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin</title>
    <!-- plugins:css -->
      <link rel="stylesheet" href="{% static 'backend/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
      <link rel="stylesheet" href="{% static 'backend/assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
      <link rel="stylesheet" href="{% static 'backend/assets/vendors/jvectormap/jquery-jvectormap.css' %}">
      <link rel="stylesheet" href="{% static 'backend/assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
      <link rel="stylesheet" href="{% static 'backend/assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
      <link rel="stylesheet" href="{% static 'backend/assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
      <link rel="stylesheet" href="{% static 'backend/assets/css/style.css' %}">
    <!-- End layout styles -->
      <link rel="shortcut icon" href="{% static 'backend/assets/images/teddy.png' %}">
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
          <!-- <a class="sidebar-brand brand-logo" href="index.html"><img src="{% static 'backend/images/logo.svg' %}" alt="logo" /></a>
          <a class="sidebar-brand brand-logo-mini" href="index.html"><img src="{% static 'backend/images/logo-mini.svg' %}" alt="logo" /></a> -->
        </div>
        <ul class="nav">
          <li class="nav-item profile">
            <div class="profile-desc">
              <div class="profile-pic">
                <div class="count-indicator">
                  <img class="img-xs rounded-circle " src="{% static 'backend/images/student.png' %}" alt="">
                  <span class="count bg-success"></span>
                </div>
                <div class="profile-name">
                  <h5 class="mb-0 font-weight-normal">{{ request.user.get_username}}</h5>
                  <span>Member</span>
                </div>
              </div>
              <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
              <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                <a href="#" class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-settings text-primary"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject ellipsis mb-1 text-small">Account settings</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-onepassword  text-info"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-calendar-today text-success"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject ellipsis mb-1 text-small">To-do list</p>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'backend:dashboard' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <!-- <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <span class="menu-icon">
                <i class="mdi mdi-laptop"></i>
              </span>
              <span class="menu-title">Basic UI Elements</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="pages/ui-features/buttons.html">Blog</a></li>
                <li class="nav-item"> <a class="nav-link" href="pages/ui-features/dropdowns.html">View Blog</a></li>
              
              </ul>
            </div>
          </li> -->

        
          <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <span class="menu-icon">
                <i class="mdi mdi-laptop"></i>
              </span>
              <span class="menu-title">Profile</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'backend:view_profile' %}">View Profile</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'backend:edit_profile' %}">Edit Profile</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'backend:change_password' %}">Change Password</a></li>
              
              </ul>
            </div>
          </li>

          <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <span class="menu-icon">
                <i class="mdi mdi-laptop"></i>
              </span>
              <span class="menu-title">Blog</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'backend:view_blog' %}">View Blog</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'backend:add_blog' %}">Add Blog</a></li>
              
              </ul>
            </div>
          </li>
        </ul>
      </nav>
      <!-- partial -->

      


      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar p-0 fixed-top d-flex flex-row">
          <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'backend/assets/images/logo-mini.svg' %}" alt="logo" /></a>
          </div>
          <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
              <span class="mdi mdi-menu"></span>
            </button>
            <ul class="navbar-nav w-100">
                <li class="nav-item w-100">
                  <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                    <input type="text" class="form-control" placeholder="Search products">
                  </form>
                </li>
              </ul>
              <ul class="navbar-nav navbar-nav-right">    
                <li class="nav-item dropdown">
                  <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                    <div class="navbar-profile">
                      <img class="img-xs rounded-circle" src="{% static 'backend/images/student.png' %}" alt="">
                      <p class="mb-0 d-none d-sm-block navbar-profile-name">Welcome  {{ request.user.get_full_name }}</p>
                      <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                    <h6 class="p-3 mb-0">Profile</h6>
                    <div class="dropdown-divider"></div>
                    
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark">
                          <i class="mdi mdi-logout text-danger"><a href="{% url 'backend:logout_view' %}">Logout</a></i>
                         
                        </div>
                      </div>
                    
                  </div>
                </li>
              </ul>
              <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-format-line-spacing"></span>
              </button>
            </div>
          </nav>
          <!-- partial -->
          {% block content %}
          {% endblock %}


          <!-- partial:partials/_footer.html -->
          <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block"></span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="" target="_blank">
            </div>
          </footer>
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'backend/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'backend/assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'backend/assets/vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'backend/assets/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
    <script src="{% static 'backend/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.j' %}s"></script>
    <script src="{% static 'backend/assets/vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'backend/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'backend/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'backend/assets/js/misc.js' %}"></script>
    <script src="{% static 'backend/assets/js/settings.js' %}"></script>
    <script src="{% static 'backend/assets/js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'backend/assets/js/dashboard.js' %}"></script>
    <!-- End custom js for this page -->
  </body>
</html>

port_project/templates/backend/change_password.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html> 

{% block title%}
Home
{% endblock %}

{% block content %}

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">Change Password</h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Change your password</a></li>
            <li class="breadcrumb-item active" aria-current="page"></li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Change your password</h4>
              <form method="post" class="forms-sample">
               {{pass_key.as_p}}
               {% csrf_token %}
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
              
              </form>
            </div>
          </div>
        </div>   
                        
                            
                            
           




{% endblock %}

port_project/templates/backend/edit-blogpost.html
{% extends 'backend/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>

{% block title %}
Home
{% endblock %}


{% block content %}


<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> Edit Post </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'backend:view_blog' %}">Forms</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit Post</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Edit your post</h4>
              <form method="post" >
               
                {% if messages %}
                {% for m in messages %}
                  <div class="alert alert-success">{{m}}</div>
  
                {% endfor %}
                {% endif %}
                {{edit.as_p}}
                {% csrf_token %}
               
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
               
              </form>
            </div>
          </div>
        </div>   
{% endblock %}                        
                            
                            

port_project/templates/backend/edit-profile.html
{% extends 'backend/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>

{% block title %}
Home
{% endblock %}


{% block content %}


<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title"> Edit Profile </h3>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Forms</a></li>
          <li class="breadcrumb-item active" aria-current="page">Edit Profile</li>
        </ol>
      </nav>
    </div>
    <div class="row">
      <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Edit your profile</h4>
            <form method="post" class="forms-sample">
              {% if messages %}
              {% for m in messages %}
                <div class="alert alert-success">{{m}}</div>

              {% endfor %}
              {% endif %}
              
             {{edit_pro.as_p}}
              <button type="submit" class="btn btn-primary mr-2">Submit</button>
             {% csrf_token %}
            </form>
          </div>
        </div>
      </div>   
    </div>
  </div>                  
                                          
{% endblock %}
          

port_project/templates/backend/signin.html
{% extends 'port_app/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
Home
{% endblock %}

{% block content %}
	
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title text-center">SignIn</h2>
              
                <form action="" method= "POST">
                {% if messages %}
                {% for m in messages %}
                <div class="alert alert-danger">{{m}}</div>
                {% endfor %}
                {% endif %}
                    <div class="input-group">
                        <label class="label">Username</label>
                           <input class="input--style-4" type="text" name="user_name">
                   </div>
                   <div class="input-group">
                       <label class="label">Password</label>
                       <input class="input--style-4" type="password" required name="password"> 
                   </div>

                       <button class="btn btn--radius-2 btn--blue" type="submit">Login</button>
                    
                    
                    <p>Don't have an account? <a href="{% url 'port_app:register' %}">Create an account</a></p>  
                    {% csrf_token %}   
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

port_project/templates/backend/view-blog.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>


{% block title %}
Home
{% endblock %}
                     

{% block content %}
        <!-- partial -->

              <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">View Blog</h4>
                    <p class="card-description">View my Blogs
                    </p>
                    <div class="table-responsive">
                      {% if not view %}
                        <h5 class="text-center">
                          No blog post
                        </h5>
                        {% else %}
                      <table class="table table-bordered">

                        <thead>
                         
                          <tr>
                            <th>S/N </th>
                            <th>Blog Title</th>
                            <th> Blog Content </th>
                            <th> Date </th>
                            <th> Action </th>
                          </tr>
                         
                          {% if view %}
                          {% for v in view %}
                          <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{v.title}}</td>
                            <td>{{v.content|truncatewords:20}}</td>
                            <td>{{v.created}}</td>
                            <td>
                              <button class="btn btn-success m-3"><a href="{% url 'backend:view_blogpost' v.slug %}">View</a></button>
                              
                          </td>
                          <td>
                            <!-- <button class="btn btn-warning m-3"><a href="{% url 'backend:editpost' v.slug %}">Edit</a></button> -->
                             
                          </td>
                          <td> <button class="btn btn-danger m-3"><a href="{% url 'backend:delete_blog' v.slug %}">Delete</a></button></td>
                          </tr>
                        {% endfor %}
                        {% endif %}
                      </table>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
              
          <!-- content-wrapper ends -->
{% endblock %}

port_project/templates/backend/viewblog_post.html
{% extends 'backend/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>

{% block title %}
Home
{% endblock %}


{% block content %}


<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> View BlogPost </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'backend:view_blog' %}">Forms</a></li>
            <li class="breadcrumb-item active" aria-current="page">Blog Post</li>
          </ol>
        </nav>
      </div>
      <div class="row d-flex">
               
    {% if post %}
        <div class="col-md-6 d-flex ftco-animate">

            <div class="blog-entry justify-content-end">
                <img class="block-20 img-fluid" src="{{post.image.url}}" alt="">
                <div >
                    <div >
                        <p class="mb-0">
                        <h5>{{post.title}}</h5>
                        <p>{{post.content}}</p>
                            
                        
                    </div>
                </div>    
            </div>
        </div>
    {% endif %}
        </div>
         
{% endblock %}                        
                            