port_project/backend/urls.py
from django.urls import path
from backend import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'backend'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('view-profile/', views.view_profile, name='view_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('view-blog/', views.view_blog, name='view_blog'),
    path('add-blog/', views.add_blog, name='add_blog'),
    path('delete_blog/<slug:slug>/', views.delete_post, name='delete_blog'),
    path('edit-blog/<slug:slug>/', views.edit_post, name='editpost'),
    path('view-blogpost/<slug:slug>/', views.view_post, name='view_blogpost'),
    path('change_password/', views.password_change, name='change_password'),
    path('logout_view-page/', views.signout, name='logout_view'),
    path('signin/',views.signin, name='signin'),
    
    
    
]

port_project/port_app/urls.py
from unicodedata import name
from django.urls import path
from port_app import views
from django.conf import settings
from django.conf.urls.static import static
from port_app.views import Blog

app_name = 'port_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
    path('register/', views.register, name='register'),
    path('blog-details/<slug:slug>/', views.blog_detail, name='detail_blog'),
    
    # path('blog-details/<slug:slug>/', views.blog_detail.as_view(model=Blog), name='detail_blog'),
   
]


port_project/port_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from port_app import  views


urlpatterns = [
    path('',views.index, name='index'),
    path('port_app/', include('port_app.urls')),
    path('', include('backend.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    
]
  

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
                         
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


port_project/port_app/models.py
from distutils.command.upload import upload
from email import message
from operator import mod
from tabnanny import verbose
from django.urls import reverse
from tkinter import CASCADE
from turtle import title
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from tinymce.models import HTMLField


# Create your models here.
class Resume(models.Model):
    year = models.CharField(max_length=20, unique=True)
    title = models.CharField(max_length=50, unique=True)
    subtitle = models.CharField(max_length=50, unique=True)
    content = models.TextField()

    def __str__(self):
        return self.title

class Skill(models.Model):
    name = models.CharField(max_length=20, unique=True)
    title = models.IntegerField()


class Blog(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    image = models.ImageField(blank=True, null=True, upload_to='upload/pics')
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    # content = HTMLField('Content')   
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
   
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
            super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def image_url(self):
        if self.image: 
            return self.image.url
        
class Blog_Approval(models.Model):
    text = models.CharField(max_length=1000)
    is_approved =models.BooleanField(default=False)
    
    def __str__(self):
        return self.text
    
        
class Comment(models.Model):
    name = models.CharField(max_length=30)
    create_on =  models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE, related_name='replies')  
                               
    class Meta:
        ordering = [ '-create_on']

    def __str__(self):
        return self.name
    
# class Reply(models.Model):
#     name = models.CharField(max_length=30)
#     create_on =  models.DateTimeField(auto_now_add=True)
#     content = models.TextField()
#     post = models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    
#     class Meta:
#         verbose_name_plural = "replies"

#     def __str__(self):
#         return self.name
    
    @property
    def children(self):
        return Comment.objects.filter(parent=self)
    
    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    subject =models.CharField(max_length=60)
    message = models.TextField()

    def __str__(self):
        return self.name
    

class Testi(models.Model):
    content = models.TextField()
    name = models.CharField(max_length=30)
    title = models.CharField(max_length=20)
    image = models.ImageField(blank=True, null=True, upload_to='upload/pics')
    
    def __str__(self):
        return self.content

    


    


    
    

port_project/port_app/views.py
from imaplib import _Authenticator
from re import template
import re
from site import USER_BASE
from statistics import mode
from unicodedata import name
from venv import create
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from port_app.models import *
from django.views.generic import ListView, DetailView, FormView
from port_app.models import Blog
from port_app.form import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash

# Create your views here.


def index(request):
    port = Resume.objects.all()
    blog = Blog.objects.order_by('-created')[:3]
    skill = Skill.objects.all()
    testi = Testi.objects.all()
    
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save(commit=False)
            return redirect('index')           
    else:
        contact_form = ContactForm()
    return render(request, 'port_app/index.html', {'port': port, 'blog':blog, 'skill': skill, 'contact': contact_form, 'reg': register, 'testi': testi}) 


def blog(request):
    blogs = Blog.objects.order_by('-created')
    return render(request, 'port_app/blog.html', {'blogs':blogs})


# class blog_detail(DetailView):
#     model = Blog
#     template_name = 'port_app/single.html'
#     content_object_name = 'detail_blog'   
    

def blog_detail(request, slug):
    detail_blog = get_object_or_404(Blog, slug=slug)
    comments = Comment.objects.filter(post__slug=slug).order_by('-create_on')
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False) 
            comment.post =  detail_blog             
            comment.save()
        return redirect(reverse('port_app:detail_blog', kwargs={'slug':slug}))
    
    else:
        form = CommentForm()
    return render(request, 'port_app/single.html', {'comm':comments, 'form':form, 'detail_blog':detail_blog})


# def blog_detail(request, slug):
#     detail_blog = get_object_or_404(Blog, slug=slug)
#     replies = Reply.objects.filter(post__slug=slug).order_by('-create_on')
#     if request.method == "POST":
#         replies = ReplyForm(request.POST)
#         if form.is_valid():
#             replies = form.save(commit=False) 
#             replies.post =  detail_blog             
#             replies.save()
#         return redirect(reverse('port_app:detail_blog', kwargs={'slug':slug}))
    
#     else:
#         form = ReplyForm()
#     return render(request, 'port_app/single.html', {'reply':replies})


def  register(request):
    if request.method =='POST':
        reg = RegisterForm(request.POST)
        if reg.is_valid():
            user = reg.save()
            login(request, user)
            return redirect("backend:signin")
    else:
        reg = RegisterForm()      
    return render(request, 'port_app/register.html', {'reg': reg})

port_project/templates/port_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="{% static 'port_app/assets/img/teddy.png' %}" rel="icon">
    <link href="{% static 'port_app/assets/img/teddy.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'port_app/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'port_app/assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'port_app/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'port_app/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'port_app/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'port_app/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'port_app/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'port_app/fonts/font-awesome-4.5.0/css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  
    <!-- Vendor CSS-->
    <link href="{% static 'port_app/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'port_app/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'port_app/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'port_app/css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'port_app/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'port_app/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'port_app/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'port_app/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'port_app/css/ionicons.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'port_app/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'port_app/css/icomoon.css' %}">
    <link href="{% static 'port_app/css/main.css' %}" rel="stylesheet" media="all">
    
    <link rel="stylesheet" href="{% static 'port_app/css/style.css' %}">
    <link href="{% static 'port_app/assets/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'port_app/css/custom.css' %}">
    <link href="{% static 'port_app/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'port_app/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
  
    <!-- Main CSS-->
    
  </head>

<body>

  <header id="header" class="fixed-top d-flex align-items-cente header-scrolled" style="border-bottom: #000000; background-color: #000000;">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0" style="font-weight: bold;"><a href="{% url 'index' %} ">Folarin</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="#home-section">Home</a></li>
          <li><a class="nav-link scrollto" href="#about-section">About</a></li>
          <li><a class="nav-link scrollto" href="#resume-section">Resume</a></li>
          <li><a class="nav-link scrollto" href="#services-section">Services</a></li>
          <li><a class="nav-link scrollto" href="#skills-section">Skills</a></li>
          <li><a class="nav-link scrollto" href="#projects-section">Projects</a></li>
          <li><a class="nav-link scrollto" href="#contact-section">Contact</a></li>
          <li><a class="nav-link scrollto" href="{% url 'port_app:blog' %}">Blog</a></li>
          <li><a class="nav-link scrollto" href="{% url 'port_app:register' %}">Register</a></li>
        </ul>   
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->
<!-- <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    </nav> --> -->
    {% block content %}
    {% endblock %}
    <footer class="ftco-footer ftco-section">
        <div class="container">
          <div class="row mb-5">
            <div class="col-md">
              <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2">About</h2>
                <p>We specialize in designing powerful branding websites that are top notch..</p>
                <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                  <li class="ftco-animate"><a href="https://www.linkedin.com/in/olubisi-folarin-1795a8236/"><span class="fa fa-linkedin-square"></span></a></li>
                  <li class="ftco-animate"><a href="mailto:hollubissy4real10@gmail.com"><span class="icon-icon icon-envelope"></span></a></li>
                  <li class="ftco-animate"><a href="https://web.facebook.com/folarin.olubisi/"><span class="icon-facebook"></span></a></li>
                  <li class="ftco-animate"><a href="https://wa.me/2348021317321"><span class="icon icon-whatsapp"></span></a></li>
                </ul>
              </div>
            </div>
            <div class="col-md">
              <div class="ftco-footer-widget mb-4 ml-md-4">
                <h2 class="ftco-heading-2"></h2>
                <ul class="list-unstyled">
                  <li><a href="#home-section"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                  <li><a href="#about-section"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                  <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                  <li><a href="#projects-section"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                  <li><a href="#contact-section"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                  <li><a href="{% url 'port_app:register' %}"><span class="icon-long-arrow-right mr-2"></span>Register</a></li>
                </ul>
              </div>
            </div>
            <div class="col-md">
               <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2">Services</h2>
                <ul class="list-unstyled">
                  <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                  <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                  <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Full Stack Development</a></li>
                  
                </ul>
              </div>
            </div>
            <div class="col-md">
              <div class="ftco-footer-widget mb-4">
                  <h2 class="ftco-heading-2">Have a Questions?</h2>
                  <div class="block-23 mb-3">
                    <ul>
                      <li><span class="icon icon-map-marker"></span><span class="text">Block 8 Plot 7 Dove Estate Ile-epo, Lagos, Nigeria</span></li>
                      <li><a href="tel://234 0821317321"><span class="icon icon-phone"></span><span class="text">+234 8021317321</span></a></li>
                      <li><a href="mailto:hollubissy4real10@gmail.com"><span class="icon icon-envelope"></span><span class="text">hollubissy4real10@gmail.com</span></a></li>
                    </ul>
                  </div>
              </div>
            </div>
          </div>
          
      </footer>
  </div>
      
    
  
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
  
    <script src="{% static 'port_app/assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'port_app/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'port_app/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'port_app/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'port_app/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'port_app/assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'port_app/assets/js/main.js' %}"></script>
    <script src="{% static 'port_app/js/jquery.min.js' %}"></script>
    <script src="{% static 'port_app/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'port_app/js/popper.min.js' %}"></script>
    <script src="{% static 'port_app/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'port_app/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'port_app/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'port_app/js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'port_app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'port_app/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'port_app/js/aos.js' %}"></script>
    <script src="{% static 'port_app/js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'port_app/js/scrollax.min.js' %}"></script>
    
    <script src="{% static 'port_app/js/main.js' %}"></script>
    <script src="{% static 'port_app/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'port_app/vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'port_app/vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'port_app/vendor/datepicker/daterangepicker.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Main JS-->
    <script src="{% static 'port_app/js/global.js' %}"></script>
      
  </body>
  </html>

port_project/templates/port_app/blog.html
{% extends 'port_app/base.html' %}
{% load static %}
<!DOCTYPE html>


  
      {% block title %}
      Blog
      {% endblock %}
    
   
    {% block content %}

	<section class="ftco-section" id="blog-section">
		<p class="text-center"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span><span class="mr-2"><a href="{% url 'port_app:blog' %}">Blog <i class="ion-ios-arrow-forward"></i></a></span></p>
		<div class="container">
			<div class="row justify-content-center mb-5 pb-5">
				<div class="col-md-7 heading-section text-center ftco-animate">
					<h1 class="big big-2">Blog</h1>
					<h2 class="mb-4">My Blog</h2>
					<p>Welcome to my blog, where u can get insight of what is happening around you.</p>
				</div>
			</div>
			
			<div class="row d-flex">
				{% if blogs %}
				{% for d in blogs %}
				<div class="col-md-4 ftco-animate">
					<div class="blog-entry justify-content-end">
						<img class="fff block-20" src="{{ d.image_url }}" alt="">
						</a>
						<div class="text mt-3 float-right d-block">
							<div class="d-flex align-items-center mb-3 meta">
								<p class="mb-0">
									<span class="mr-2"></span>
									<a href="#" class="mr-2">{{d.poster}}</a>
									<a href="#" class="meta-chat"><span class="icon-chat">{{d.created}}</span></a>
								</p>
							</div>
							<div>
							<h3 class="heading">{{ d.title }}</h3>
							<p>{{ d.content|slice:":50" }}</p>
							<a href="{% url 'port_app:detail_blog' d.slug %}" class="btn btn-warning">READ MORE &rrarr;</a>
							</div>
						</div>
					
					</div>
				
			  	</div>
				{% endfor %}
				{% endif %}
    		</div>
		</div>
    </section>


{% endblock %}  

		

port_project/templates/port_app/register.html
{% extends 'port_app/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>

{% block title%}
Home
{% endblock %}

{% block content %}


<div class="page-wrapper backgr p-t-130 p-b-100 font-poppins">
    <p class="text-center"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span><span class="mr-2"><a href="{% url 'port_app:register' %}">Register<i class="ion-ios-arrow-forward"></i></a></span></p>
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title text-center">Registration Form</h2>
                <form action="" method= "POST">
                      
                   {{reg.as_p}}
                   <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                   {% csrf_token %}
                <p class="text-dark text-center">If you already have an account <a href="{% url 'backend:signin' %}">Signin</a></p>  
                       
               
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

port_project/templates/port_app/single.html
{% extends 'port_app/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
{{detail_blog.title}}
{% endblock %}

{% block content %}

	  <section class="hero-wrap js-fullheight" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
            <h1 class="mb-3 bread">Blog Single Post</h1>
              <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{% url 'port_app:blog' %}">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row">
          {% if detail_blog %}
          <div class="col-lg-8 ftco-animate">
            <h2 class="mb-3">{{detail_blog.created}}</h2>
            <p>{{detail_blog.title}}</p>
            <p>
              <img src="{{detail_blog.image_url}}" alt="" class="img-fluid">
            </p>  
            <p>{{detail_blog.content}}</p>
            
          {% endif %}
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">Life</a>
                <a href="#" class="tag-cloud-link">Sport</a>
                <a href="#" class="tag-cloud-link">Tech</a>
                <a href="#" class="tag-cloud-link">Travel</a>
              </div>
            </div>
            
            <div class="about-author d-flex p-4 bg-dark">
              <div class="bio mr-5">
                  <img src="{% static 'port_app/images/student.png' %}" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc">
                <h3>George Washington</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
              </div>
            </div>

              
            
              
              {% with comments.count as total_comments %}
              <h3>{{total_comments}} Comment {{total_comments|pluralize}}</h3>
              {% endwith %}
              <ul class="comment-list">
                {% if comm %}
                {% for c in comm %}
                <li class="comment">
                  <div class="vcard bio">
                    <img src="{% static 'port_app/images/student.png' %}" alt="Image placeholder">
                  </div>
                    <div class="comment-body">
                      <h3>{{c.name}}</h3>
                    <div class="meta">{{c.create_on}}</div>
                      <p>{{c.content}}</p>
                </li>
                {% endfor %}
                {% endif %}

              
              </ul>
              <ul>
                   

              <!-- END comment-list -->
              
              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Leave a comment</h3>
                <form action="" method="POST" class="p-5 bg dark" enctype="multipart/form-data">
                 
                    
                      {{ form.as_p}}
                      {% csrf_token %}
              
                      <div class="form-group">
                        <input type="submit" value="Post" class="btn py-3 px-4 btn-primary" style="width:30%;">
                        <!-- <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                          Reply
                        </button> -->
                      </div>
                </div>
              </form>
              
            

          </div>
        </div>
      </div>   
              <!-- END comment-list -->
              <!-- Button trigger modal -->


<!-- Modal -->
<!-- <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="collapse" id="collapse{{comm.id}}"></div>
                <form action="" method="POST" class="p-5 bg dark" enctype="multipart/form-data">
                    {{ form.as_p}}
                    {% csrf_token %}
                  
                      <input type="hidden" placeholder="Reply" name="parent_id" value="{{ comm.id }}">
                      <input class="btn btn-primary" style="width: 30%;" type="submit" value="Reply">
                  
                </form>
           
      </div>   
      
    </div>
  </div>
</div> -->
  
    </section> <!-- .section -->
		
{% endblock %}